spring.application.name=loginpage
server.port=8080

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/mylogin
spring.datasource.username=spike
spring.datasource.password=alla
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
